/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CallbackExample_CallbackData */

#ifndef _Included_CallbackExample_CallbackData
#define _Included_CallbackExample_CallbackData
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
