/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CallbackExample */

#ifndef _Included_CallbackExample
#define _Included_CallbackExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CallbackExample
 * Method:    registerCallback
 * Signature: (ILCallbackExample/Callback;)V
 */
JNIEXPORT void JNICALL Java_CallbackExample_registerCallback
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     CallbackExample
 * Method:    startBusiness
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_CallbackExample_startBusiness
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
